### ISSUE TITLE
Container crash

### ISSUE THREAD

**Issue by lennvilardi** [GabrielRF/Video2Telegram#6]
Hi,
The container crash regurlaly. Any idea to correct this problem ?
Here's the output :

2020-05-01 05:41:29 | stdout | inotify.calls.InotifyError: Call failed (should not be -1): (-1) ERRNO=(0)
-- | -- | --
2020-05-01 05:41:29 | stdout | (result,))
2020-05-01 05:41:29 | stdout | File "/usr/local/lib/python2.7/dist-packages/inotify/calls.py", line 35, in _check_nonnegative
2020-05-01 05:41:29 | stdout | inotify.calls.inotify_rm_watch(self.__inotify_fd, wd)
2020-05-01 05:41:29 | stdout | File "/usr/local/lib/python2.7/dist-packages/inotify/adapters.py", line 126, in remove_watch_with_id
2020-05-01 05:41:29 | stdout | self.remove_watch_with_id(wd)
2020-05-01 05:41:29 | stdout | File "/usr/local/lib/python2.7/dist-packages/inotify/adapters.py", line 118, in remove_watch
2020-05-01 05:41:29 | stdout | self._i.remove_watch(full_path, superficial=True)
2020-05-01 05:41:29 | stdout | File "/usr/local/lib/python2.7/dist-packages/inotify/adapters.py", line 309, in event_gen
2020-05-01 05:41:29 | stdout | for event in notifier.event_gen():
2020-05-01 05:41:29 | stdout | File "./file2gif.py", line 17, in <module>
2020-05-01 05:41:29 | stdout | Traceback (most recent call last):
2020-04-30 22:11:06 | stdout | inotify.calls.InotifyError: Call failed (should not be -1): (-1) ERRNO=(0)
2020-04-30 22:11:06 | stdout | (result,))
2020-04-30 22:11:06 | stdout | File "/usr/local/lib/python2.7/dist-packages/inotify/calls.py", line 35, in _check_nonnegative
2020-04-30 22:11:06 | stdout | inotify.calls.inotify_rm_watch(self.__inotify_fd, wd)
2020-04-30 22:11:06 | stdout | File "/usr/local/lib/python2.7/dist-packages/inotify/adapters.py", line 126, in remove_watch_with_id
2020-04-30 22:11:06 | stdout | self.remove_watch_with_id(wd)
2020-04-30 22:11:06 | stdout | File "/usr/local/lib/python2.7/dist-packages/inotify/adapters.py", line 118, in remove_watch
2020-04-30 22:11:06 | stdout | self._i.remove_watch(full_path, superficial=True)
2020-04-30 22:11:06 | stdout | File "/usr/local/lib/python2.7/dist-packages/inotify/adapters.py", line 309, in event_gen
2020-04-30 22:11:06 | stdout | for event in notifier.event_gen():
2020-04-30 22:11:06 | stdout | File "./file2gif.py", line 17, in <module>
2020-04-30 22:11:06 | stdout | Traceback (most recent call last):
2020-04-30 05:31:22 | stdout | inotify.calls.InotifyError: Call failed (should not be -1): (-1) ERRNO=(0)
2020-04-30 05:31:22 | stdout | (result,))
2020-04-30 05:31:22 | stdout | File "/usr/local/lib/python2.7/dist-packages/inotify/calls.py", line 35, in _check_nonnegative
2020-04-30 05:31:22 | stdout | inotify.calls.inotify_rm_watch(self.__inotify_fd, wd)
2020-04-30 05:31:22 | stdout | File "/usr/local/lib/python2.7/dist-packages/inotify/adapters.py", line 126, in remove_watch_with_id
2020-04-30 05:31:22 | stdout | self.remove_watch_with_id(wd)
2020-04-30 05:31:22 | stdout | File "/usr/local/lib/python2.7/dist-packages/inotify/adapters.py", line 118, in remove_watch
2020-04-30 05:31:22 | stdout | self._i.remove_watch(full_path, superficial=True)
2020-04-30 05:31:22 | stdout | File "/usr/local/lib/python2.7/dist-packages/inotify/adapters.py", line 309, in event_gen
2020-04-30 05:31:22 | stdout | for event in notifier.event_gen():
2020-04-30 05:31:22 | stdout | File "./file2gif.py", line 17, in <module>
2020-04-30 05:31:21 | stdout | Traceback (most recent call last):

**Comment by GabrielRF** [comment]
@lennvilardi Is it still ok?

**Comment by lennvilardi** [comment]
No still got crash 
`2020-05-23T04:52:00.554827339Z Traceback (most recent call last):

2020-05-23T04:52:00.708765307Z   File "./file2gif.py", line 17, in <module>

2020-05-23T04:52:00.708941493Z     for event in notifier.event_gen():

2020-05-23T04:52:00.709006558Z   File "/usr/local/lib/python2.7/dist-packages/inotify/adapters.py", line 309, in event_gen

2020-05-23T04:52:00.850584675Z     self._i.remove_watch(full_path, superficial=True)

2020-05-23T04:52:00.850752551Z   File "/usr/local/lib/python2.7/dist-packages/inotify/adapters.py", line 118, in remove_watch

2020-05-23T04:52:00.850822569Z     self.remove_watch_with_id(wd)

2020-05-23T04:52:00.850870959Z   File "/usr/local/lib/python2.7/dist-packages/inotify/adapters.py", line 126, in remove_watch_with_id

2020-05-23T04:52:00.850923784Z     inotify.calls.inotify_rm_watch(self.__inotify_fd, wd)

2020-05-23T04:52:00.850972195Z   File "/usr/local/lib/python2.7/dist-packages/inotify/calls.py", line 35, in _check_nonnegative

2020-05-23T04:52:00.851025303Z     (result,))

2020-05-23T04:52:00.851068749Z inotify.calls.InotifyError: Call failed (should not be -1): (-1) ERRNO=(0)
`
